name: Deploy to Azure
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Connexion au registre Docker (ACR)
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Construction et Envoi de l'image
    - run: |
        docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/monapp:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/monapp:latest

    # Mise à jour de la Web App
    # Remplace 'projetdjango-webapp' par le nom EXACT défini dans ton main.tf (resource azurerm_linux_web_app)
    - name: Deploy via Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'projetdjango-webapp' 
        images: '${{ secrets.ACR_LOGIN_SERVER }}/monapp:latest'